server:
  servlet:
    context-path: /bs-account-service
    
logging:
  file:
    name: account-service.log
    max-history: 1
    path: /var/logs
  level:
    root: warn
    com.mycompany.bs: debug
  